# permissions for end users to view puzzledbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: puzzledb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: puzzledb-operator
    app.kubernetes.io/part-of: puzzledb-operator
    app.kubernetes.io/managed-by: kustomize
  name: puzzledb-viewer-role
rules:
- apiGroups:
  - apiextensions.k8s.io.cybergarage.org
  resources:
  - puzzledbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io.cybergarage.org
  resources:
  - puzzledbs/status
  verbs:
  - get
